version: 2

models:
  - name: dim_dates
    description: "Date dimension table with comprehensive date attributes"
    columns:
      - name: date_sk
        description: "Primary key - date in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: date_value
        description: "Actual date value"
        tests:
          - not_null
      - name: year
        description: "Year extracted from date"
        tests:
          - not_null
      - name: quarter
        description: "Quarter (1-4)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
      - name: month
        description: "Month (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: day_of_month
        description: "Day of month (1-31)"
        tests:
          - not_null
      - name: day_of_week
        description: "Day of week (1=Sunday, 7=Saturday)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]
      - name: is_weekend
        description: "Boolean flag for weekend (Saturday/Sunday)"
        tests:
          - not_null
      - name: day_name
        description: "Full day name (Monday, Tuesday, etc.)"
      - name: month_name
        description: "Full month name (January, February, etc.)"
      - name: week_of_year
        description: "Week number within the year"
      - name: is_business_day
        description: "Boolean flag for business days (Monday-Friday)"
        tests:
          - not_null
  - name: dim_order_reviews
    description: "Order reviews dimension table with sentiment and derived columns"
    columns:
      - name: review_sk
        description: "Surrogate key for review"
        tests:
          - unique
          - not_null
      - name: review_id
        description: "Review ID"
        tests:
          - not_null
      - name: order_id
        description: "Order ID"
      - name: review_score
        description: "Score given in review"
      - name: review_comment_title
        description: "Title of the review comment"
      - name: review_comment_message
        description: "Message of the review comment"
      - name: review_creation_date
        description: "Date review was created"
      - name: review_answer_timestamp
        description: "Timestamp when review was answered"
      - name: review_sentiment
        description: "Derived sentiment from score"
      - name: has_comment
        description: "Boolean flag for presence of comment"
      - name: has_answer
        description: "Boolean flag for presence of answer"
      - name: review_year
        description: "Year of review creation"
      - name: review_month
        description: "Month of review creation"
  - name: dim_products
    description: "Products dimension table with translations and derived columns"
    columns:
      - name: product_sk
        description: "Surrogate key for product"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Product ID"
        tests:
          - not_null
      - name: product_category_name
        description: "Original product category name"
      - name: product_category_name_english
        description: "Translated product category name"
      - name: product_name_lenght
        description: "Length of product name"
      - name: product_description_lenght
        description: "Length of product description"
      - name: product_photos_qty
        description: "Number of product photos"
      - name: product_weight_g
        description: "Product weight in grams"
      - name: product_length_cm
        description: "Product length in cm"
      - name: product_height_cm
        description: "Product height in cm"
      - name: product_width_cm
        description: "Product width in cm"
      - name: product_weight_kg
        description: "Product weight in kilograms (derived)"
      - name: product_volume_cm3
        description: "Product volume in cm^3 (derived)"
      - name: photo_quality_category
        description: "Photo quality category (derived)"
  - name: dim_customers
    description: "Customers dimension table with region and location columns"
    columns:
      - name: customer_sk
        description: "Surrogate key for customer"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer ID"
        tests:
          - not_null
      - name: customer_unique_id
        description: "Unique customer identifier"
      - name: customer_zip_code_prefix
        description: "Zip code prefix"
      - name: customer_city
        description: "City of customer"
      - name: customer_state
        description: "State of customer"
      - name: customer_state_code
        description: "Uppercase state code (derived)"
      - name: customer_location
        description: "Concatenated city and state (derived)"
      - name: customer_region
        description: "Region of customer (derived)"
  - name: dim_sellers
    description: "Sellers dimension table with region and location columns"
    columns:
      - name: seller_sk
        description: "Surrogate key for seller"
        tests:
          - unique
          - not_null
      - name: seller_id
        description: "Seller ID"
        tests:
          - not_null
      - name: seller_zip_code_prefix
        description: "Zip code prefix"
      - name: seller_city
        description: "City of seller"
      - name: seller_state
        description: "State of seller"
      - name: seller_state_code
        description: "Uppercase state code (derived)"
      - name: seller_location
        description: "Concatenated city and state (derived)"
      - name: seller_region
        description: "Region of seller (derived)"
  - name: dim_orders
    description: "Orders dimension table with delivery and derived columns"
    columns:
      - name: order_sk
        description: "Surrogate key for order"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Order ID"
        tests:
          - not_null
      - name: customer_id
        description: "Customer ID"
      - name: order_status
        description: "Status of order"
      - name: order_purchase_timestamp
        description: "Timestamp of purchase"
      - name: order_approved_at
        description: "Timestamp of approval"
      - name: order_delivered_carrier_date
        description: "Carrier delivery date"
      - name: order_delivered_customer_date
        description: "Customer delivery date"
      - name: order_estimated_delivery_date
        description: "Estimated delivery date"
      - name: order_year
        description: "Year of purchase (derived)"
      - name: order_month
        description: "Month of purchase (derived)"
      - name: order_day
        description: "Day of purchase (derived)"
      - name: delivery_days
        description: "Days taken for delivery (derived)"
      - name: is_delivered
        description: "Boolean flag for delivered orders (derived)"
  - name: dim_geolocations
    description: "Geolocations dimension table with region and geographic calculations"
    columns:
      - name: geolocation_sk
        description: "Surrogate key for geolocation"
        tests:
          - unique
          - not_null
      - name: geolocation_zip_code_prefix
        description: "Zip code prefix"
        tests:
          - not_null
      - name: geolocation_lat
        description: "Latitude"
      - name: geolocation_lng
        description: "Longitude"
      - name: geolocation_city
        description: "City"
      - name: geolocation_state
        description: "State"
      - name: geolocation_state_code
        description: "Uppercase state code (derived)"
      - name: geolocation_location
        description: "Concatenated city and state (derived)"
      - name: geolocation_region
        description: "Region (derived)"
      - name: geolocation_lat_rounded
        description: "Latitude rounded to 4 decimals (derived)"
      - name: geolocation_lng_rounded
        description: "Longitude rounded to 4 decimals (derived)"
  - name: dim_payments
    description: "Payments dimension table with installment and value categories"
    columns:
      - name: payment_sk
        description: "Surrogate key for payment"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Order ID"
        tests:
          - not_null
      - name: payment_sequential
        description: "Sequential number of payment for order"
      - name: payment_type
        description: "Type of payment"
      - name: payment_installments
        description: "Number of installments"
      - name: payment_value
        description: "Value of payment"
      - name: installment_category
        description: "Installment category (derived)"
      - name: payment_value_category
        description: "Payment value category (derived)"
      - name: installment_amount
        description: "Amount per installment (derived)"
