version: 1
default_environment: dev
project_id: 0198cf5e-5994-79cf-b139-fa589862c550
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: postgres
      filter_schemas:
      - public
      host: aws-1-ap-southeast-1.pooler.supabase.com
      port: 5432
      user: postgres.royhmnxmsfichopabwsi
      password: $TAP_POSTGRES_PASSWORD
      max_record_count: 0
    select:
    - public-olist_customers_dataset.*
    - public-olist_order_items_dataset.*
    - public-olist_order_payments_dataset.*
    - public-olist_order_reviews_dataset.*
    - public-olist_orders_dataset.*
    - public-olist_products_dataset.*
    - public-olist_sellers_dataset.*
    - public-olist_geolocation_dataset.*
    - public-product_category_name_translation.*
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      batch_size: 1000
      credentials_path: ./bigquery-credentials.json
      project: $BQ_PROJECT_ID
      dataset: $TARGET_RAW_DATASET
      location: $BQ_LOCATION
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: streaming_insert
      overwrite: false
      add_record_metadata: false
      table_suffix: ""
      stream_maps:
        public-olist_customers_dataset:
          __alias__: customers
        public-olist_geolocation_dataset:
          __alias__: geolocation
        public-olist_order_items_dataset:
          __alias__: order_items
        public-olist_order_payments_dataset:
          __alias__: order_payments
        public-olist_order_reviews_dataset:
          __alias__: order_reviews
        public-olist_orders_dataset:
          __alias__: orders
        public-olist_products_dataset:
          __alias__: products
        public-olist_sellers_dataset:
          __alias__: sellers
        public-product_category_name_translation:
          __alias__: product_category_name_translation

# Jobs configuration
  transformers:
  - name: dbt-bigquery
    variant: dbt-labs
    pip_url: dbt-core~=1.3.0 dbt-bigquery~=1.3.0
    config:
      project_dir: transform
      profiles_dir: transform/profiles
      target: prod
      source_schema: $TARGET_STAGING_DATASET
      target_schema: $TARGET_BIGQUERY_DATASET
jobs:
- name: supabase-to-bigquery
  tasks:
  - tap-postgres target-bigquery-supabase
- name: supabase-to-bigquery-with-transform
  tasks:
  - tap-postgres target-bigquery-supabase
  - dbt-bigquery:run
  - dbt-bigquery:test

# Hooks for automated cleanup
hooks:
  post-invoke:
    tap-postgres:
    - python meltano-post-hook.py
    target-bigquery:
    - python meltano-post-hook.py
    target-bigquery-supabase:
    - python meltano-post-hook.py
  post-run:
    supabase-to-bigquery:
    - python meltano-post-hook.py

