version: 2

sources:
  - name: raw
    description: "Raw dataset from Supabase containing raw olist e-commerce data"
    database: "{{ env_var('BQ_PROJECT_ID') }}"
    schema: "{{ env_var('TARGET_RAW_DATASET', 'olist_raw') }}"
    tables:
      - name: customers
        description: "Customer information including location and unique identifiers"
        
      - name: geolocation
        description: "Geolocation data with latitude, longitude, and location details"
        
      - name: order_items
        description: "Individual items within orders including product, seller, and pricing information"
        
      - name: order_payments
        description: "Payment information for orders including payment type and amounts"
        
      - name: order_reviews
        description: "Customer reviews and ratings for orders"
        
      - name: orders
        description: "Order header information including status, timestamps, and customer references"
        
      - name: products
        description: "Product catalog information including categories, dimensions, and weights"
        
      - name: product_category_name_translation
        description: "Translation mapping for product category names"
        
      - name: sellers
        description: "Seller information including location and unique identifiers"