version: 2

sources:
  - name: staging
    description: "Raw dataset from Supabase containing raw olist e-commerce data"
    database: "{{ env_var('BQ_PROJECT_ID') }}"
    schema: "{{ env_var('TARGET_RAW_DATASET', 'olist_data_raw') }}"
    description: "Source data from Olist e-commerce platform"
    tables:
      - name: supabase_olist_customers_dataset
        description: "Customer information including location and unique identifiers"
        
      - name: supabase_olist_geolocation_dataset
        description: "Geolocation data with latitude, longitude, and location details"
        
      - name: supabase_olist_order_items_dataset
        description: "Individual items within orders including product, seller, and pricing information"
        
      - name: supabase_olist_order_payments_dataset
        description: "Payment information for orders including payment type and amounts"
        
      - name: supabase_olist_order_reviews_dataset
        description: "Customer reviews and ratings for orders"
        
      - name: supabase_olist_orders_dataset
        description: "Order header information including status, timestamps, and customer references"
        
      - name: supabase_olist_products_dataset
        description: "Product catalog information including categories, dimensions, and weights"
        
      - name: supabase_product_category_name_translation
        description: "Translation mapping for product category names"
        
      - name: supabase_olist_sellers_dataset
        description: "Seller information including location and unique identifiers"