version: 2

models:
  # =============================================================================
  # FACT TABLE
  # =============================================================================
  - name: fact_order_items
    description: "Central fact table containing all measurable metrics for order item analysis. Grain: One row per order item (most granular level)."
    meta:
      owner: "data_team"
      layer: "warehouse"
      business_purpose: "Core transactional fact table for order item analysis"
    
    columns:
      - name: order_item_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
      
      - name: order_id
        description: "Natural key for order identification"
        tests:
          - not_null
          - relationships:
              to: ref('dim_orders')
              field: order_id
      
      - name: order_item_id
        description: "Natural key for item within order"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 50
      
      - name: order_sk
        description: "Foreign key to dim_orders"
        tests:
          - not_null
          - relationships:
              to: ref('dim_orders')
              field: order_sk
      
      - name: customer_sk
        description: "Foreign key to dim_customer"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_sk
      
      - name: product_sk
        description: "Foreign key to dim_product"
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_sk
      
      - name: seller_sk
        description: "Foreign key to dim_seller"
        tests:
          - not_null
          - relationships:
              to: ref('dim_seller')
              field: seller_sk
      
      - name: payment_sk
        description: "Foreign key to dim_payment (nullable - some orders may not have payments)"
        tests:
          - relationships:
              to: ref('dim_payment')
              field: payment_sk
      
      - name: review_sk
        description: "Foreign key to dim_order_reviews (nullable - not all orders have reviews)"
        tests:
          - relationships:
              to: ref('dim_order_reviews')
              field: review_sk
      
      - name: order_date_sk
        description: "Foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_sk
      
      - name: shipping_limit_date_sk
        description: "Foreign key to dim_date (nullable - some orders may not have shipping limits)"
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_sk
      
      - name: customer_geography_sk
        description: "Foreign key to dim_geolocation (nullable - geography data may be incomplete)"
        tests:
          - relationships:
              to: ref('dim_geolocation')
              field: geolocation_sk
      
      - name: seller_geography_sk
        description: "Foreign key to dim_geolocation (nullable - geography data may be incomplete)"
        tests:
          - relationships:
              to: ref('dim_geolocation')
              field: geolocation_sk
      
      - name: price
        description: "Item price (additive measure)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 10000
              config:
                severity: warn
      
      - name: freight_value
        description: "Shipping cost (additive measure)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1000
              config:
                severity: warn
      
      - name: payment_value
        description: "Allocated payment amount (additive measure)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 15000
              config:
                severity: warn
      
      - name: payment_installments
        description: "Number of payment installments"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 24
              config:
                severity: warn
      
      - name: review_score
        description: "Customer review score (1-5, nullable if no review)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 5
              config:
                severity: warn
      
      - name: insertion_timestamp
        description: "Audit timestamp for when record was inserted"
        tests:
          - not_null

  # =============================================================================
  # DIMENSION TABLES
  # =============================================================================
  - name: dim_customer
    description: "Customer dimension with enhanced data quality flags and regional analysis"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: customer_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
      
      - name: customer_id
        description: "Natural key for customer"
        tests:
          - not_null
          - unique
      
      - name: customer_state
        description: "Customer's state"
        tests:
          - not_null
          - accepted_values:
              values: ['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']

  - name: dim_product
    description: "Product dimension with category translations and quality flags"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: product_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
      
      - name: product_id
        description: "Natural key for product"
        tests:
          - not_null
          - unique

  - name: dim_seller
    description: "Seller dimension with geographic and quality information"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: seller_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
      
      - name: seller_id
        description: "Natural key for seller"
        tests:
          - not_null
          - unique

  - name: dim_orders
    description: "Order dimension with lifecycle tracking and delivery metrics"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: order_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
      
      - name: order_id
        description: "Natural key for order"
        tests:
          - not_null
          - unique

  - name: dim_payment
    description: "Payment dimension with method classification and fraud indicators"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: payment_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique

  - name: dim_geolocation
    description: "Geographic dimension for location-based analysis"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: geolocation_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
      
      - name: geolocation_zip_code_prefix
        description: "ZIP code prefix"
        tests:
          - not_null

  - name: dim_date
    description: "Time dimension for temporal analysis"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: date_sk
        description: "Surrogate key (Primary Key) - YYYYMMDD format"
        tests:
          - not_null
          - unique
      
      - name: date_value
        description: "Actual date value"
        tests:
          - not_null
          - unique

  - name: dim_order_reviews
    description: "Order review dimension with sentiment analysis"
    meta:
      owner: "data_team"
      layer: "warehouse"
    
    columns:
      - name: review_sk
        description: "Surrogate key (Primary Key)"
        tests:
          - not_null
          - unique
