version: 2

sources:
  - name: warehouse
    description: "Warehouse models dataset"
    database: "{{ env_var('BQ_PROJECT_ID') }}"
    schema:  "{{ env_var('TARGET_BIGQUERY_DATASET', 'dbt_olist_dwh') }}"
    tables:
      - name: dim_customer
        description: "Warehouse customers data"
      - name: dim_orders
        description: "Warehouse orders data"
      - name: dim_order_items
        description: "Warehouse order items data"
      - name: dim_order_reviews
        description: "Warehouse order reviews data"
      - name: dim_payment
        description: "Warehouse payments data"
      - name: dim_product
        description: "Warehouse products data"
      - name: dim_seller
        description: "Warehouse sellers data"
      - name: dim_geolocation
        description: "Warehouse geolocations data"
      - name: dim_date
        description: "Warehouse dates data"
      - name: fact_order_items
        description: "Warehouse fact order items data"

