austin_bikeshare_demo:
  outputs:
    dev:
      dataset: austin_bikeshare_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: infinite-byte-458600-a8
      threads: 1
      type: bigquery
  target: dev
bec_dbt:
  outputs:
    dev:
      dataset: olist_data_warehouse
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: bec_dbt/dsai-468212-key.json
      location: US
      method: service-account
      priority: interactive
      project: dsai-468212
      threads: 5
      type: bigquery
  target: dev
resale_flat:
  outputs:
    dev:
      dataset: resale
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: infinite-byte-458600-a8
      threads: 5
      type: bigquery
  target: dev
