austin_bikeshare_demo:
  outputs:
    dev:
      dataset: austin_bikeshare_demo
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: project-olist-470307
      threads: 1
      type: bigquery
  target: dev
bec_dbt:
  outputs:
    dev:
      dataset: "{{ env_var('TARGET_STAGING_DATASET', 'dbt_olist_stg') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS_PATH', 'service-account-key.json') }}"
      location: "{{ env_var('BQ_LOCATION', 'asia-southeast1') }}"
      priority: interactive
      threads: 5
      type: bigquery
    warehouse:
      dataset: "{{ env_var('TARGET_BIGQUERY_DATASET', 'dbt_olist_dwh') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS_PATH', 'service-account-key.json') }}"
      location: "{{ env_var('BQ_LOCATION', 'asia-southeast1') }}"
      priority: interactive
      threads: 5
      type: bigquery
    analytics:
      dataset: "{{ env_var('TARGET_ANALYTICAL_DATASET', 'dbt_olist_analytics') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      method: service-account
      project: "{{ env_var('BQ_PROJECT_ID') }}"
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS_PATH', 'service-account-key.json') }}"
      location: "{{ env_var('BQ_LOCATION', 'asia-southeast1') }}"
      priority: interactive
      threads: 5
      type: bigquery
  target: dev
resale_flat:
  outputs:
    dev:
      dataset: resale
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: project-olist-470307
      threads: 5
      type: bigquery
  target: dev
